name: Tweet Scraper

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node CronJob/tweetPeriodicScraper.js
        working-directory: ${{ github.workspace }}
